<a href="https://colab.research.google.com/github/Eglasiuk/Eglasiuk/blob/main/Intro_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys

import numpy as np
print(np.__version__)

1.20.3


# Creación de numpy arrays

In [ ]:
array_1d = np.array([4,5, 3])
type(array_1d)

numpy.ndarray

In [ ]:
array_1d.shape

(3,)

In [ ]:
array_1d.ndim

1

In [ ]:
matriz = np.array([
    [ 1,2, 1 ],
    [5, 43, 5]
])

matriz

array([[ 1,  2,  1],
       [ 5, 43,  5]])

In [ ]:
matriz.shape

(2, 3)

In [ ]:
matriz.ndim

2

`np.eye` crea una matriz identidad de tamaño 3x3

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`np.zeros` crea un array con todos los valores a 0

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

`np.ones` crea un vector de longitud 3 inicializado con todos los valores 1 (${\vec {1}}$)

In [ ]:
np.ones(3)

array([1., 1., 1.])

`np.random` produce un array con valores aleatorios en el intervalo [0, 1)

In [ ]:
np.random.random((2,3))

array([[0.84161878, 0.32426274, 0.84108528],
       [0.69883733, 0.92716129, 0.2214295 ]])

podemos leer tambien texto y convertirlo en un np.array

In [ ]:
!cat np_text.txt

1,2,3
43, 2,3
34,1,1
0,1,1

In [ ]:
np_text = np.genfromtxt("np_text.txt", delimiter=",")
np_text

array([[ 1.,  2.,  3.],
       [43.,  2.,  3.],
       [34.,  1.,  1.],
       [ 0.,  1.,  1.]])

# Ventajas de np.array versus lists

In [ ]:
array_1d = np.array([1,2,3])

In [ ]:
array_1d.shape

(3,)

In [ ]:
lista_2d = [[1222,2222,2223], [5,23,40004]]

array_2d = np.array([[1222,2222,2223], [5,23,40004]])

print("Tamaño de la lista en memoria: {} bytes".format(sys.getsizeof(lista_2d)))
print("Tamaño del numpy array en memoria: {} bytes".format(sys.getsizeof(array_2d)))

Tamaño de la lista en memoria: 72 bytes
Tamaño del numpy array en memoria: 168 bytes


No obstante, cuando trabajamos con cantidades grandes, numpy empieza a funcionar mejor

In [ ]:
big_list = list(range(100000000))
big_array = np.array(range(100000000))

print("Tamaño de la lista en memoria: {} bytes".format(sys.getsizeof(big_list)))
print("Tamaño del numpy array en memoria: {} bytes".format(sys.getsizeof(big_array)))

Tamaño de la lista en memoria: 800000056 bytes
Tamaño del numpy array en memoria: 800000104 bytes


`%%timeit` es un magic de jupyter que evalua el tiempo que tarda una celda en computar, al pasarle el parámetro -n=10 le decimos que queremos que  mida el tiempo corriendo el código 10 veces

In [ ]:
%%timeit -n 10
sum(range(10000000))

204 ms ± 9.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%%timeit -n 10
np.sum(np.arange(10000000))

23.4 ms ± 1.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Vemos que la operación con np.arrays es 10x más rápida

Para poder utilizar todo el potencial de utilizacion numerica de numpy, todos los elementos del numpy array tienen que ser del mismo tipo, si no lo son, numpy intenta convertir los elementos a un sólo tipo. Numpy hace eso para poder hacer operaciones vectorizadas.

In [ ]:
np.array([1.0, 5.4])

array([1. , 5.4])

In [ ]:
np.array([1, 3.9])

array([1. , 3.9])

hacemos `dtype` para ver el tipo de datos que almacena el array.

In [ ]:
np.array([1, 3.9]).dtype

dtype('float64')

In [ ]:
np.array([1, "1"])

array(['1', '1'], dtype='<U21')

Si no puede optimizar un array, numpy lo creara con el tipo `object`, en el que trabajara simplemente con objetos de python.

In [ ]:
from datetime import datetime

np.array([1, datetime.utcnow()])

array([1, datetime.datetime(2021, 5, 22, 17, 13, 30, 413378)],
      dtype=object)

In [ ]:
%%timeit
["{}".format(i) for i in range(10000000)]

2.6 s ± 127 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
f = np.vectorize(lambda x: "{}".format(x))

In [ ]:
%%timeit
f(np.arange(10000000))

5.12 s ± 775 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
["{}".format(i) for i in np.arange(10000000)]

4.34 s ± 225 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Seleccion por secciones y por indices (slicing e indexing)

In [ ]:
matriz_34 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

obtenemos la primera fila igual que con una lista normal

In [ ]:
matriz_34[0]

array([1, 2, 3, 4])

seleccionamos la 1 y 2 fila

In [ ]:
matriz_34[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Seleccionamos el 2 elemento de cada fila (o sea, la segunda columna de la matriz)

In [ ]:
matriz_34[:,1]

array([ 2,  6, 10])

al seleccionar secciones no obtenemos copias, sino referencias al mismo array

In [ ]:
seccion = matriz_34[:2,:]
seccion

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print(matriz_34[0,1])
seccion[0, 0] = 0
matriz_34

2


array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Sin embargo, al seleccionar un elemento esto no pasa

In [ ]:
seleccion = matriz_34[1,3]
print(seleccion)
seleccion = 100
matriz_34

8


array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Filtrado

In [ ]:
matriz_32 = np.array([[1, 4], [2, 4], [5, 0]])
matriz_32

array([[1, 4],
       [2, 4],
       [5, 0]])

In [ ]:
indice_fitrado = (matriz_32 >= 2)
indice_fitrado

array([[False,  True],
       [ True,  True],
       [ True, False]])

In [ ]:
matriz_32[indice_fitrado]

array([4, 2, 4, 5])

## Aritmetica con numpy arrays

In [ ]:
array1 = np.array([[2,3],[0,1]])
array2 = np.array([[23,6],[0,42]])

print(array1)
print(array2)

[[2 3]
 [0 1]]
[[23  6]
 [ 0 42]]


suma elemento a elemento

In [ ]:
array1 + array2

array([[25,  9],
       [ 0, 43]])

multiplicación elemento a elemento

In [ ]:
array1 * array2

array([[46, 18],
       [ 0, 42]])

Desde python 3.5, podemos usar el simbolo `@` para indicar una multiplicación de matrices (para versiones anteriores se usa la funcion `dot`

In [ ]:
array1 @ array2

array([[ 46, 138],
       [  0,  42]])

equivale a 

In [ ]:
array1.dot(array2)

array([[ 46, 138],
       [  0,  42]])

# Links

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

https://www.quantopian.com/posts/quantopian-lecture-series-introduction-to-numpy

https://www.datacamp.com/community/tutorials/python-numpy-tutorial#gs.HwYuvYI